### ISSUE TITLE
Import biomass: Passo Gavia 2017-2021

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#181]

**Comment by KW529** [comment]
Dear Melinda and Kate, 

As requested in your last IDE call, I'm sending you the updated datasheets concerning the alpine IDE site, Passo Gavia (Italy).  

Biomass and cover data for the third (2020) and fourth (2021) treatment year have been added. We have corrected a few cover values for 2017 and 2019 on the basis of 2020-2021 sampling and of cross-checking of data and notes regarding observations made in the field. Two new taxa have also been added. All changes made compared to the previous datasheet we sent you in May 2020 are highlighted in yellow and all new annotations and changes of particular data fields have also been reported in yellow in all the sheets of the file.  

We are also sending you the climate datasheet in which updated precipitation and temperature data is reported. In this sheet you will also find corrections made compared to the previous file we sent you in October 2019 (highlighted in yellow). 

As communicated in our previous mail, in this last treatment season we have collected soil samples for C and N analysis, as this is the 4th year since the beginning of the experiment. We did this according to the indications reported on the protocol. We would like to know if you want us to send this material, who is the person we have to send it to and when you want us to ship it. For your knowledge, the delivery address we sent the sample in 2018 was the one indicated in the guidelines for shipping IDE soil samples (attached to this e-mail). 

Concerning the results of analysis on soil samples of the pre-treatment year (2017), would it be possible for you to send us the data, if these are available? We are interested to see the values for our site, also in view of other research we are carrying out. This data would be very useful for us. 

Finally, we also wanted to let you know that we have indirect estimations of aboveground biomass for the 1 m2 permanent plots in our IDE site (for period 2017-2021) – so far, we have sent you values deriving from direct ANPP measurements gathered from destructive harvesting. Let us know if you are interested in having this data as well as the one we have already sent you. 

Please feel free to contact me or the other members of the research team (in cc to this mail) if you have any questions or concerns. 

Hope you are all well and looking forward to hearing from you.  

Best wishes, 

Alessandro, Michele and T'ai

**Comment by tim-ohlert** [comment]
Dear Timothy,

This is T'ai Forte, from University of Parma (Italy). I'm writing regarding the DroughtNet check passogavia.it you sent yesterday to Alessandro Petraglia (cc to this mail). I just wanted to ask you a few infos on the graph you sent before proceeding with the check.

What are the "Drought years" you report in the graph? To me it seems like they refer to years 2019-2021. If so, it means it's the 2-4 year of drought treatment for our site and 2018, the first year, is missing. Am I correct? And, in the case, why is that?

How did you calculate "Average ANPP"? Did you do the sum of vascular taxa (grasses, forbs and shrubs) for each plot and each year and then calculated the mean of the 5 plots for each treatment and each year? Or did you follow another procedure? If so, it would be helpful to know so we can do a proper check.

Thanks in advance!

Best wishes,

T'ai

**Comment by tim-ohlert** [comment]
Hi T'ai

Here is a more transparent figure that I think will help answers some questions. Each point is ANPP from a single plot and you are correct that the data in the previous figure incorrectly was only years 2019-2021. 

I believe the ANPP values include forbs, graminoids, shrubs, and bryophytes. We are particularly interested in what looks like an outlier drought treatment plot in 2021.

Thanks,
Tim

**Comment by tim-ohlert** [comment]
Dear Timothy,

Thanks for the info! We managed to check the data and confirm that everything is correct. Below a graph which we have produced with our original dataset and cross-checking it with that you sent data seems identical.

Regarding the outlier you pointed out in 2021, which refers to plot 10, we checked again if there were any typos by verifying the original lab sheets we filled in when weighting the sample; we confirm there are no mistakes. The sample had simply a lot of bryophytes in it (see figure below), which is something that, to some degree, is independent from the drought treatment and more related to casual moss distribution in the site.

In fact, regarding this point, we believe that summing bryophytes and vascular plants could generate some noise in the data and mosses do not represent ANPP since their biomass doesn't reflect the year production.

Let us know if there is anything else that needs to be checked, we are happy to be of any help!

Looking forward on updates!



Best wishes,

T'ai and Alessandro
